#!/usr/bin/env bash

# Credit: adapted from @dbalatero's dotfiles at:
#
#   https://raw.githubusercontent.com/dbalatero/dotfiles/
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

print_in_color() {
  printf "%b" \
    "$(tput setaf "$2" 2> /dev/null)" \
    "$1" \
    "$(tput sgr0 2> /dev/null)"
  }

print_in_purple() {
  print_in_color "$1" 5
}

print_header() {
  print_in_purple "\n • $1\n\n"
}

print_success() {
  print_in_green "   [✔] $1\n"
}

run_osx_script() {
  if [[ $(uname) == "Darwin" ]]; then
    print_header "Applying OS X tweaks..."

    $HOME/.dotfiles/osx

    echo
    print_success "OSX tweaks applied"
  fi
}

clone_dotfiles_repo() {
  print_header "Cloning dotfiles repo..."

  if [[ -d ~/.dotfiles ]]; then
    print_success "dotfiles repo already cloned to ~/.dotfiles"
  else
    git clone git@github.com:dbalatero/dotfiles.git ~/.dotfiles
    print_success "cloned dotfile repo"

    echo "Now you can run: cd ~/.dotfiles && ./setup"
  fi
}

main() {
  clone_dotfiles_repo
  run_osx_script
}

main
