#!/usr/bin/env bash

_colorized() {
   echo "$@" | sed -E \
     -e 's/((@(red|green|yellow|blue|magenta|cyan|white|reset|b|u))+)[[]{2}(.*)[]]{2}/\1\4@reset/g' \
     -e "s/@red/$(tput setaf 1)/g" \
     -e "s/@green/$(tput setaf 2)/g" \
     -e "s/@yellow/$(tput setaf 3)/g" \
     -e "s/@blue/$(tput setaf 4)/g" \
     -e "s/@magenta/$(tput setaf 5)/g" \
     -e "s/@cyan/$(tput setaf 6)/g" \
     -e "s/@white/$(tput setaf 7)/g" \
     -e "s/@reset/$(tput sgr0)/g" \
     -e "s/@b/$(tput bold)/g" \
     -e "s/@u/$(tput sgr 0 1)/g"
}

dotsay() {
  local result=$(_colorized $@)
  echo "$result"
}

dotheader() {
  dotsay "@b@green[[$1]]"
  echo
}

function dotfiles_location() {
  # echo "$HOME/.dotfiles"
  echo "$HOME/github/dotfiles"
}

function ensure_plugin_directory() {
  mkdir -p ~/.local/share/nvim/plugged
}

function symlink_dotfile() {
  local file=$1
  local destination=$2
  local full_file_path="$(dotfiles_location)/$file"

  if [ ! -e $destination ]; then
    dotsay "++ Symlinking $full_file_path -> $destination"
    mkdir -p "$(dirname $destination)"
    ln -s $full_file_path $destination
  fi
}

function command_exists() {
  local name=$1

  command -v "$name" >/dev/null 2>&1
}

function brew_install() {
  local package=$1

  if brew list "$package" > /dev/null 2>&1; then
    dotsay "+ $package already installed... skipping."
  else
    brew install $@
  fi
}

function setup_neovim_config() {
  dotsay "@b@blue[[+ Setting up nvim config]]"
  mkdir -p ~/.config
  symlink_dotfile nvim ~/.config/nvim
}

function install_neovim_plugins() {
  dotsay "@b@blue[[+ Installing nvim plugins]]"
  nvim +PlugInstall +qall
}

function install_coc_plugins() {
  dotsay "@b@blue[[+ Installing coc plugins]]"
  # gem install solargraph

  nvim \
    +"CocInstall coc-json coc-solargraph coc-css coc-html coc-syntax coc-snippets coc-tsserver coc-emmet coc-github-users coc-go" \
    +qall
}

function install_proximity_sort() {
  dotsay "@b@blue[[+ Installing proximity sort]]"
  if ! command_exists "proximity-sort" ; then
    cargo install --force proximity-sort
  fi
}

function install_neovim() {
  dotsay "@b@blue[[+ Installing neovim]]"
    brew_install neovim --HEAD
}

install_neovim
setup_neovim_config
ensure_plugin_directory
install_neovim_plugins
install_coc_plugins
